/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlink.jpackage.test;

import java.io.IOException;

import javax.swing.JOptionPane;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

//        System.in.read();	// fail to start jvm in the image, no console? how to make console app?

        JOptionPane.showMessageDialog(null, "Hello World!");
    }
}
